// Given two strings s and t which consist of only lowercase letters.

// String t is generated by random shuffling string s and then add one more letter at a random position.

// Find the letter that was added in t.

// Example:

// Input:
// s = "abcd"
// t = "abcde"

// Output:
// e

// Explanation:
// 'e' is the letter that was added.

// two solution
class Solution {
public:
    char findTheDifference(string s, string t) {
        int s_int = 0, t_int=0;
        for(auto it: s){
            s_int+= it-'a';
        }
        for(auto it: t){
            t_int+= it-'a';
        }
        t_int-=s_int;
        char ans = t_int+'a';
        return ans;
    }
    char findTheDifference(string s, string t) {
        char r=0;
        for(char c:s) r ^=c;
        for(char c:t) r ^=c;
        return r;
    }
};